import os
import sys
import subprocess
import hashlib
import shutil
import time
from pathlib import Path
from systems.os.platform import is_windows, get_venv_python_path

# --- CONFIGURATION ---
CWD = Path(__file__).parent
CORE_APPS_DIR = CWD / "apps"
EXTENSIONS_DIR = CWD / "extensions"
CORE_REQS_FILE = CWD / "requirements.core.in"
FINAL_REQS_IN = CWD / "requirements.in"
FINAL_REQS_TXT = CWD / "requirements.txt"
VENV_DIR = CWD / ".venv"
REQS_HASH_FILE = VENV_DIR / ".reqs-hash"
RESTART_CODE = 100

def get_uv_command():
    """Finds the uv executable."""
    uv = shutil.which("uv")
    if not uv:
        # Fallback for Windows if uv is installed in standard location but not in PATH
        possible_uv = Path(os.environ.get("USERPROFILE", "")) / ".cargo" / "bin" / "uv.exe"
        if possible_uv.exists():
            return str(possible_uv)
    return uv

def scan_requirements() -> str:
    """
    Scans core/apps and extensions for requirements.txt, merges them with core requirements.
    Returns the combined string content.
    """
    lines = []
    
    # 1. Header
    lines.append("# This file is auto-generated by launch.py. DO NOT EDIT.")
    lines.append(f"# Base: {CORE_REQS_FILE.name}")
    
    # 2. Core requirements
    if CORE_REQS_FILE.exists():
        lines.append(CORE_REQS_FILE.read_text(encoding='utf-8').strip())
    
    # 3. Extensions
    search_dirs = [CORE_APPS_DIR, EXTENSIONS_DIR]
    found_exts = []
    
    for root_dir in search_dirs:
        if not root_dir.exists():
            continue
        
        for item in root_dir.iterdir():
            if item.is_dir():
                req_file = item / "requirements.txt"
                if req_file.exists():
                    found_exts.append(item.name)
                    lines.append(f"\n# Extension: {item.name}")
                    content = req_file.read_text(encoding='utf-8').strip()
                    # Basic cleanup to avoid adding empty lines
                    lines.append(content)

    print(f"[Launcher] Found requirements in extensions: {', '.join(found_exts) if found_exts else 'None'}")
    return "\n".join(lines)

def needs_update(content: str) -> bool:
    """Checks if requirements have changed based on hash."""
    if not VENV_DIR.exists() or not FINAL_REQS_TXT.exists():
        return True
    
    current_hash = hashlib.md5(content.encode('utf-8')).hexdigest()
    
    if REQS_HASH_FILE.exists():
        stored_hash = REQS_HASH_FILE.read_text(encoding='utf-8').strip()
        if stored_hash == current_hash:
            return False
            
    return True

def update_environment(content: str):
    """Updates requirements.in, compiles to .txt, and syncs venv using uv."""
    uv = get_uv_command()
    if not uv:
        print("[Launcher] ERROR: 'uv' command not found.")
        print("[Launcher] Please run 'install.bat' to set up the required tools.")
        sys.exit(1)

    print("[Launcher] Dependencies changed. Updating environment...")
    
    # 1. Write requirements.in
    FINAL_REQS_IN.write_text(content, encoding='utf-8')
    
    # 2. Create Venv if missing
    if not VENV_DIR.exists():
        print("[Launcher] Creating virtual environment...")
        subprocess.run([uv, "venv"], check=True)

    # 3. Compile (resolve versions)
    print("[Launcher] Compiling requirements...")
    try:
        subprocess.run([uv, "pip", "compile", str(FINAL_REQS_IN), "-o", str(FINAL_REQS_TXT)], check=True)
    except subprocess.CalledProcessError:
        print("[Launcher] ERROR: Failed to compile requirements. Check your requirements.core.in or extension dependencies.")
        return

    # 4. Sync (install/uninstall)
    print("[Launcher] Syncing environment...")
    subprocess.run([uv, "pip", "sync", str(FINAL_REQS_TXT)], check=True)
    
    # 5. Update Hash
    new_hash = hashlib.md5(content.encode('utf-8')).hexdigest()
    REQS_HASH_FILE.write_text(new_hash, encoding='utf-8')
    print("[Launcher] Environment up to date.")

def get_python_exe():
    """Returns the path to the venv python interpreter."""
    return Path(get_venv_python_path(CWD))

def run_app():
    """Main execution loop with restart capability."""
    
    # --- Initial Environment Check ---
    print("[Launcher] Performing initial environment check...")
    try:
        if is_windows():
            script_name = "check_environment.bat"
            if os.path.exists(script_name):
                subprocess.call([script_name], shell=True)
        else:
            script_name = "./check_environment.sh"
            if os.path.exists("check_environment.sh"):
                # Ensure executable permissions
                os.chmod("check_environment.sh", 0o755)
                subprocess.call([script_name])
    except Exception as e:
        print(f"[Launcher] Could not run environment check: {e}")
    
    
    # --- Dependency Check Phase ---
    try:
        reqs_content = scan_requirements()
        if needs_update(reqs_content):
            update_environment(reqs_content)
    except Exception as e:
        print(f"[Launcher] Error during dependency check: {e}")
        # We continue to try running the app, maybe it works
    
    python_exe = get_python_exe()
    if not python_exe.exists():
        # Fallback to system python if venv failure (risky but allows recovery scripts)
        print(f"[Launcher] Venv python not found at {python_exe}. Using system python.")
        python_exe = Path(sys.executable)

    cmd = [str(python_exe), "-m", "core.app"] + sys.argv[1:]
    
    # --- Execution Phase ---
    while True:
        print(f"[Launcher] Starting application...")
        process = subprocess.Popen(cmd, cwd=CWD)
        process.wait()
        
        return_code = process.returncode
        
        if return_code == RESTART_CODE:
            print("[Launcher] Restart signal received. Rebooting...")
            time.sleep(1)
            continue
            
        elif return_code == 0:
            print("[Launcher] Application exited normally.")
            break
            
        else:
            print(f"[Launcher] Application crashed with code {return_code}.")
            print("[Launcher] Attempting to run recovery utility...")
            try:
                subprocess.run([str(python_exe), "restore.py"], cwd=CWD)
            except Exception as e:
                print(f"[Launcher] Failed to run recovery: {e}")
            break

if __name__ == "__main__":
    run_app()