import json
from typing import Tuple

def parse(args_list: list) -> bool:
    if '-nodejs' in args_list:
        return True
    return False

def run(fs, launch_file: str, dependencies: list, project_name: str, npm_command = None, platforms: set = None) -> Tuple[bool, str]:
    try:
        platforms = platforms or {'win', 'unix'} # Default to all
        # 1. Create package.json
        deps_dict = {}
        for dep in dependencies:
            if '@' in dep and not dep.startswith('@'):
                name, ver = dep.rsplit('@', 1)
                deps_dict[name] = ver
            else:
                deps_dict[dep] = "*"

        main_entry = launch_file

        # Default scripts
        scripts_map = {}
        run_cmd_bat = "npm run start"
        
        # --- Logic for determining scripts and run command ---
        if npm_command:
            if isinstance(npm_command, dict):
                # Advanced Mode: -npm <run:{...}|scripts/start:{...}>
                # 1. Merge scripts
                scripts_map.update(npm_command.get('scripts', {}))
                
                # 2. Determine BAT command
                if npm_command.get('run'):
                    run_cmd_bat = f'cmd /c "{npm_command["run"]}"'
                elif 'start' in scripts_map:
                    run_cmd_bat = "npm run start"
                else:
                    # Fallback if no run cmd and no start script provided explicitly
                    run_cmd_bat = "npm run dev" if "dev" in scripts_map else "npm run start"
            
            else:
                # Simple Mode: -npm <{cmd}>
                scripts_map["start"] = npm_command
                run_cmd_bat = f'cmd /c "{npm_command}"'
        else:
            # Fallback (No -npm arg): Use -run <file>
            if launch_file.endswith('.js') or launch_file.endswith('.ts'):
                scripts_map["start"] = f"node {launch_file}"
                run_cmd_bat = "npm run start"
            else:
                # -run contained a command, not a file
                scripts_map["start"] = launch_file
                run_cmd_bat = "npm run start"
                main_entry = "index.js"

        # Auto-detect 'dev' script if using vite and not explicitly set
        if "vite" in dependencies and "dev" not in scripts_map:
            scripts_map["dev"] = "vite"

        package_json = {
            "name": project_name.lower().replace(" ", "-").replace("(", "").replace(")", ""),
            "version": "1.0.0",
            "description": "Generated by ELAI-DevKit",
            "main": main_entry,
            "scripts": scripts_map,
            "keywords": [],
            "author": "",
            "license": "ISC",
            "dependencies": deps_dict
        }

        fs.write("@ROOT/package.json", json.dumps(package_json, indent=2))

        files_created = []

        # 2. Create Launch Scripts
        if 'win' in platforms:
            bat_content = get_nodejs_run_bat_template().format(
                project_name=project_name,
                run_command=run_cmd_bat
            )
            fs.write("@ROOT/run(nodejs).bat", bat_content)
            files_created.append("Windows (.bat)")

        if 'unix' in platforms:
            # Determine bash compatible run command
            run_cmd_sh = "npm run start"
            if npm_command and isinstance(npm_command, dict):
                # If 'run' was provided, we assume it's a cross-platform command or user knows what they are doing
                # But typically 'npm run start' is safer as abstraction
                if npm_command.get('run'):
                    # Clean up "cmd /c" if present for cross-platform usage
                    clean_cmd = npm_command['run'].replace('cmd /c ', '').replace('"', '')
                    run_cmd_sh = clean_cmd
                elif 'start' in scripts_map:
                    run_cmd_sh = "npm run start"
            elif npm_command:
                # Simple mode
                run_cmd_sh = npm_command

            sh_content = get_nodejs_run_sh_template().format(
                project_name=project_name,
                run_command=run_cmd_sh
            )
            fs.write_bytes("@ROOT/run(nodejs).sh", sh_content.replace('\r\n', '\n').encode('utf-8'))
            files_created.append("Unix (.sh)")

        return True, f"NodeJS environment files created for: {', '.join(files_created)}."
    except Exception as e:
        return False, f"Error creating nodejs files: {e}"

def get_nodejs_run_bat_template():
    return """
@echo off
setlocal
cls

echo ============================================
echo      {project_name} (NodeJS Mode)
echo ============================================
echo.

REM --- STAGE 1: Check Environment ---
call :prepare_env
IF %ERRORLEVEL% NEQ 0 (
    echo.
    echo Environment preparation failed. Exiting.
    pause
    exit /b 1
)

REM --- STAGE 2: Run Application ---
echo.
echo --- Starting Application ---
echo Command: {run_command}
{run_command}

echo.
echo --- Application exited. Press any key to close. ---
pause
goto :eof

:prepare_env
    echo [1/2] Checking Node.js installation...
    node -v >nul 2>&1
    IF %ERRORLEVEL% NEQ 0 (
        echo [ERROR] Node.js is not installed or not in PATH.
        exit /b 1
    )

    echo [2/2] Checking Dependencies...
    IF NOT EXIST node_modules (
        echo    - 'node_modules' not found. Installing dependencies...
        call npm install
        IF %ERRORLEVEL% NEQ 0 exit /b 2
    ) ELSE (
        echo    - Dependencies found. Skipping install.
    )
    goto :eof
"""

def get_nodejs_run_sh_template():
    return """
#!/bin/bash
echo "============================================"
echo "      {project_name} (NodeJS Mode)"
echo "============================================"
echo ""

# --- STAGE 1: Check Environment ---
if ! command -v node &> /dev/null; then
    echo "[ERROR] Node.js is not installed."
    exit 1
fi

if [ ! -d "node_modules" ]; then
    echo "   - 'node_modules' not found. Installing dependencies..."
    npm install
    if [ $? -ne 0 ]; then exit 1; fi
else
    echo "   - Dependencies found."
fi

# --- STAGE 2: Run Application ---
echo ""
echo "--- Starting Application ---"
{run_command}
"""

from typing import List, Tuple

def tests(vfs) -> List[Tuple[str, bool, str]]:
    res =[]
    succ, msg = run(vfs, 'index.js', ['express'], 'TestNode', None, {'win', 'unix'})
    passed = succ and vfs.exists('@ROOT/package.json') and vfs.exists('@ROOT/run(nodejs).bat')
    res.append(("NodeJS Env Generate", passed, msg))
    return res
